#!/usr/bin/env bash

if [ -e ".secrets" ]; then
  source ".secrets"
  echo "Secrets loaded; target S3 bucket: ${AWS_BUCKET}, endpoint: ${CD_FOR_DOWNLOADS_API_ENDPOINT}"
fi

act -C test \
  -j upload \
  -v \
  -s AWS_KEY_ID=${AWS_KEY_ID} \
  -s AWS_SECRET_ACCESS_KEY_ID=${AWS_SECRET_ACCESS_KEY_ID} \
  -s AWS_BUCKET=${AWS_BUCKET} \
  -s AWS_REGION=${AWS_REGION} \
  -s CD_FOR_DOWNLOADS_USERNAME=${CD_FOR_DOWNLOADS_USERNAME} \
  -s CD_FOR_DOWNLOADS_APPLICATION_PASSWORD="${CD_FOR_DOWNLOADS_APPLICATION_PASSWORD}" \
  --env CD_FOR_DOWNLOADS_API_ENDPOINT="${CD_FOR_DOWNLOADS_API_ENDPOINT}" \
  --env CD_FOR_DOWNLOADS_VERSION="$CD_FOR_DOWNLOADS_VERSION"\
  --env CD_FOR_DOWNLOADS_PRODUCT_ID=${CD_FOR_DOWNLOADS_PRODUCT_ID}


