name: Run tests on branch commit
on:
  workflow_call:

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        php: [ "8.1" ]
        phpunit: [ "9.5.10" ]

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6

    - name: PHPStan
      id: phpstan
      run: |
        vendor/bin/phpstan analyse

    - name: PHPUnit test
      uses: php-actions/phpunit@v2
      with:
        php_version: ${{ matrix.php }}
        version: ${{ matrix.phpunit }}
        php_extensions: ldap mbstring
        configuration: phpunit.xml
        args: --coverage-text --verbose