name: Create pre-release for GitHub-only
on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    name: Build and Test
    uses: ./.github/workflows/build_and_test.yml

  variables:
    needs: build_and_test
    name: Detect Git and release variables
    uses: dreitier/github-workflows/.github/workflows/variables.yml@main
    with:
      package: continuous-delivery
      is_official_release: false

  package_and_deploy:
    runs-on: ubuntu-latest
    needs: variables
    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          # even with a (pre-)release, we need all dev-dependencies so that strauss can repackage the namespaces.
          # we exclude the then-unnecessary vendor/ directory in the "Zip all files" step.
          dev: yes

      - name: Set job variables
        id: zip_variables
        run: |
          echo "zip_file=${ARTIFACT_NAME}.zip"  >> $GITHUB_OUTPUT
        env:
          ARTIFACT_NAME: ${{ needs.variables.outputs.artifact_name }}

      - name: Update version tag
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "@VERSION@"
          replace: ${{ needs.variables.outputs.version }}

      - name: ZIP workspace
        id: zip
        uses: schakko/action-zip-workspace@main
        with:
          filename: ${{ steps.zip_variables.outputs.zip_file }}
          subdirectory: ${{ needs.variables.outputs.package }}

      - name: Upload release to GitHub
        id: upload
        uses: ncipollo/release-action@v1
        with:
          artifacts:  ${{ steps.zip_variables.outputs.zip_file }}
          allowUpdates: true
          tag: ${{ needs.variables.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}