name: Create pre-release for GitHub-only
on:
  push:
    branches:
      - main
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        php: [ "8.1" ]
        phpunit: [ "9.5.10" ]

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6

    - name: PHPUnit test
      uses: php-actions/phpunit@v2
      with:
        php_version: ${{ matrix.php }}
        version: ${{ matrix.phpunit }}
        php_extensions: ldap mbstring
        configuration: phpunit.xml
        args: --coverage-text --verbose

  prerelease:
    runs-on: ubuntu-latest
    needs: testing
    name: Create pre-release
    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6
      with:
        # even with a (pre-)release, we need all dev-dependencies so that strauss can repackage the namespaces.
        # we exclude the then-unnecessary vendor/ directory in the "Zip all files" step.
        dev: yes

    - name: Set environment variable
      id: vars
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Replace version string
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "REPLACE_VERSION_BY_CI"
        replace: ${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}

    - name: PHPStan
      id: phpstan
      run: |
        vendor/bin/phpstan analyse

    - name: Zip all files
      run: zip -r release.zip . -x ".git/*" ".github/*" -x "vendor/* -x test/* -x phpstan.*"

    - name: Upload pre-release to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}-continuous-delivery-pre-release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
