name: Create pre-release for GitHub-only
on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    uses: ./.github/workflows/build.yml

  prerelease:
    runs-on: ubuntu-latest
    needs: testing
    name: Create pre-release
    env:
      PACKAGE: continuous-delivery

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          # even with a (pre-)release, we need all dev-dependencies so that strauss can repackage the namespaces.
          # we exclude the then-unnecessary vendor/ directory in the "Zip all files" step.
          dev: yes

      - uses: dreitier/github-workflows/.github/workflows/variables.yml@main
        id: variables
        with:
          package: ${{ env.PACKAGE }}
          is_official_release: false

      - uses: dreitier/github-workflows/.github/workflows/package.yml@main
        id: packaging
        with:
          artifact_name: ${{ steps.variables.outputs.artifact_name }}
          version: ${{ steps.variables.outputs.version }}
