name: Official release on wordpress.org
on:
  push:
    tags:
      - '*'

env:
  PACKAGE: continuous-delivery

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  checkout:
    runs-on: ubuntu-latest
    needs: testing
    name: Release plug-in
    env:
      PACKAGE: continuous-delivery

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6
      with:
        # even with a (pre-)release, we need all dev-dependencies so that strauss can repackage the namespaces.
        # we exclude the then-unnecessary vendor/ directory in the "Zip all files" step.
        dev: yes

  variables:
    uses: dreitier/github-workflows/.github/workflows/variables.yml@main
    with:
      package: ${{ env.PACKAGE }}
      is_official_release: false

  package:
    uses: dreitier/github-workflows/.github/workflows/package.yml@main
    with:
      artifact_name: ${{ needs.variables.outputs.artifact_name }}
      version: ${{ needs.variables.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: WordPress Plugin Deploy
      uses: schakko/action-wordpress-plugin-deploy@develop
      with:
        generate-zip: true
        dry-run: false
      env:
        SVN_USERNAME: ${{ secrets.WORDPRESS_ORG_SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.WORDPRESS_ORG_SVN_PASSWORD }}
        SLUG: continuous-delivery
