name: Official release on wordpress.org
on:
  push:
    tags:
      - '*'

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        php: [ "8.1" ]
        phpunit: [ "9.5.10" ]

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6

    - name: PHPUnit test
      uses: php-actions/phpunit@v2
      with:
        php_version: ${{ matrix.php }}
        version: ${{ matrix.phpunit }}
        php_extensions: ldap mbstring
        configuration: phpunit.xml
        args: --coverage-text --verbose

  release:
    runs-on: ubuntu-latest
    needs: testing
    name: Release plug-in
    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6
      with:
        # even with a (pre-)release, we need all dev-dependencies so that strauss can repackage the namespaces.
        # we exclude the then-unnecessary vendor/ directory in the "Zip all files" step.
        dev: yes

    - name: Set environment variable
      run: echo "CURRENT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Replace version string
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "REPLACE_VERSION_BY_CI"
        replace: ${{ env.CURRENT_TAG }}

    - name: PHPStan
      id: phpstan
      run: |
        vendor/bin/phpstan analyse

    - name: WordPress Plugin Deploy
      uses: schakko/action-wordpress-plugin-deploy@develop
      with:
        generate-zip: true
        dry-run: false
      env:
        SVN_USERNAME: ${{ secrets.WORDPRESS_ORG_SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.WORDPRESS_ORG_SVN_PASSWORD }}
        SLUG: continuous-delivery
    
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "continuous-delivery.zip"
        token: ${{ secrets.GITHUB_TOKEN }}