name: Official release on wordpress.org
on:
  push:
    tags:
      - '*'

jobs:
  build_and_test:
    name: Build and Test
    uses: ./.github/workflows/build_and_test.yml

  variables:
    needs: build_and_test
    name: Detect Git and release variables
    uses: dreitier/github-workflows/.github/workflows/variables.yml@main
    with:
      package: continuous-delivery
      is_official_release: false

  package_and_deploy:
    runs-on: ubuntu-latest
    needs: variables
    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6
      with:
        # even with a (pre-)release, we need all dev-dependencies so that strauss can repackage the namespaces.
        # we exclude the then-unnecessary vendor/ directory in the "Zip all files" step.
        dev: yes

    - name: Set variables
      id: zip_variables
      run: |
        echo "::set-output name=zip_file::${ARTIFACT_NAME}.zip"
      env:
        ARTIFACT_NAME: ${{ needs.variables.outputs.artifact_name }}

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "@VERSION@"
        replace: ${{ needs.variables.outputs.version }}

    - name: ZIP workspace
      id: zip
      uses: schakko/action-zip-workspace@main
      with:
        filename: ${{ steps.zip_variables.outputs.zip_file }}
        subdirectory: ${{ needs.variables.outputs.package }}

    - name: Upload releases to GitHub
      id: upload
      uses: ncipollo/release-action@v1
      with:
        artifacts:  ${{ steps.zip_variables.outputs.zip_file }}
        allowUpdates: true
        tag: ${{ steps.variables.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: WordPress Plugin Deploy
      uses: schakko/action-wordpress-plugin-deploy@develop
      with:
        generate-zip: true
        dry-run: false
      env:
        SVN_USERNAME: ${{ secrets.WORDPRESS_ORG_SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.WORDPRESS_ORG_SVN_PASSWORD }}
        SLUG: continuous-delivery
